import { StyleSheet } from '@react-pdf/renderer';
import { invoiceTokens } from './invoiceTokens';

export const createInvoiceStyles = (accentColor = invoiceTokens.colors.accent) =>
  StyleSheet.create({
    page: {
      paddingTop: 24,
      paddingBottom: 24,
      paddingLeft: 28,
      paddingRight: 28,
      fontFamily: invoiceTokens.fontFamily.sans,
      fontSize: invoiceTokens.fontSize.md,
      color: invoiceTokens.colors.text,
      backgroundColor: invoiceTokens.colors.background,
    },
    headerRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: invoiceTokens.spacing.md,
      paddingBottom: invoiceTokens.spacing.sm,
      borderBottomWidth: invoiceTokens.border.regular,
      borderBottomColor: invoiceTokens.colors.border,
    },
    title: {
      fontSize: invoiceTokens.fontSize.title,
      fontWeight: 'bold',
      color: accentColor,
      textTransform: 'uppercase',
    },
    subtitle: {
      fontSize: invoiceTokens.fontSize.xs,
      color: invoiceTokens.colors.muted,
      marginTop: invoiceTokens.spacing.xxs,
    },
    businessName: {
      fontSize: invoiceTokens.fontSize.lg,
      fontWeight: 'bold',
      color: invoiceTokens.colors.text,
      marginBottom: invoiceTokens.spacing.xxs,
    },
    businessDetail: {
      fontSize: invoiceTokens.fontSize.xs,
      color: invoiceTokens.colors.muted,
      lineHeight: 1.3,
    },
    partiesContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: invoiceTokens.spacing.md,
      gap: invoiceTokens.spacing.md,
    },
    partyBox: {
      flex: 1,
      padding: invoiceTokens.spacing.sm,
      backgroundColor: invoiceTokens.colors.tableHeaderBg,
      borderRadius: 4,
      borderWidth: invoiceTokens.border.thin,
      borderColor: invoiceTokens.colors.lightBorder,
    },
    partyTitle: {
      fontSize: invoiceTokens.fontSize.xs,
      fontWeight: 'bold',
      color: accentColor,
      textTransform: 'uppercase',
      marginBottom: invoiceTokens.spacing.xs,
    },
    partyName: {
      fontSize: invoiceTokens.fontSize.sm,
      fontWeight: 'bold',
      color: invoiceTokens.colors.text,
      marginBottom: invoiceTokens.spacing.xxs,
    },
    partyText: {
      fontSize: invoiceTokens.fontSize.xs,
      color: invoiceTokens.colors.muted,
      lineHeight: 1.3,
    },
    metaBox: {
      width: 180,
      padding: invoiceTokens.spacing.sm,
      backgroundColor: invoiceTokens.colors.tableHeaderBg,
      borderRadius: 4,
      borderWidth: invoiceTokens.border.thin,
      borderColor: invoiceTokens.colors.lightBorder,
    },
    metaRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: invoiceTokens.spacing.xxs,
    },
    metaLabel: {
      fontSize: invoiceTokens.fontSize.xs,
      color: invoiceTokens.colors.muted,
    },
    metaValue: {
      fontSize: invoiceTokens.fontSize.xs,
      fontWeight: 'bold',
      color: invoiceTokens.colors.text,
    },
    table: {
      width: '100%',
      marginBottom: invoiceTokens.spacing.md,
      borderWidth: invoiceTokens.border.thin,
      borderColor: invoiceTokens.colors.border,
    },
    tableHeader: {
      flexDirection: 'row',
      backgroundColor: accentColor,
      paddingVertical: invoiceTokens.spacing.xs,
      paddingHorizontal: invoiceTokens.spacing.xs,
    },
    tableHeaderCell: {
      color: '#ffffff',
      fontSize: invoiceTokens.fontSize.xs,
      fontWeight: 'bold',
      textTransform: 'uppercase',
    },
    tableRow: {
      flexDirection: 'row',
      borderBottomWidth: invoiceTokens.border.thin,
      borderBottomColor: invoiceTokens.colors.lightBorder,
      paddingVertical: invoiceTokens.spacing.xs,
      paddingHorizontal: invoiceTokens.spacing.xs,
      alignItems: 'center',
    },
    tableRowAlt: {
      backgroundColor: invoiceTokens.colors.tableHeaderBg,
    },
    tableCell: {
      fontSize: invoiceTokens.fontSize.xs,
      color: invoiceTokens.colors.text,
    },
    totalsContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginTop: invoiceTokens.spacing.sm,
      marginBottom: invoiceTokens.spacing.md,
    },
    wordsBox: {
      flex: 1,
      marginRight: invoiceTokens.spacing.md,
      padding: invoiceTokens.spacing.sm,
      backgroundColor: invoiceTokens.colors.tableHeaderBg,
      borderRadius: 4,
      borderWidth: invoiceTokens.border.thin,
      borderColor: invoiceTokens.colors.lightBorder,
    },
    wordsTitle: {
      fontSize: invoiceTokens.fontSize.xxs,
      fontWeight: 'bold',
      color: invoiceTokens.colors.muted,
      textTransform: 'uppercase',
      marginBottom: invoiceTokens.spacing.xxs,
    },
    wordsText: {
      fontSize: invoiceTokens.fontSize.xs,
      fontWeight: 'bold',
      color: invoiceTokens.colors.text,
    },
    totalsBox: {
      width: 220,
      borderWidth: invoiceTokens.border.thin,
      borderColor: invoiceTokens.colors.border,
      borderRadius: 4,
      overflow: 'hidden',
    },
    totalRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingVertical: invoiceTokens.spacing.xxs,
      paddingHorizontal: invoiceTokens.spacing.sm,
      borderBottomWidth: invoiceTokens.border.thin,
      borderBottomColor: invoiceTokens.colors.lightBorder,
    },
    totalRowGrand: {
      backgroundColor: accentColor,
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingVertical: invoiceTokens.spacing.xs,
      paddingHorizontal: invoiceTokens.spacing.sm,
    },
    totalLabelGrand: {
      fontSize: invoiceTokens.fontSize.sm,
      fontWeight: 'bold',
      color: '#ffffff',
    },
    totalValueGrand: {
      fontSize: invoiceTokens.fontSize.sm,
      fontWeight: 'bold',
      color: '#ffffff',
    },
    termsBox: {
      padding: invoiceTokens.spacing.sm,
      backgroundColor: invoiceTokens.colors.tableHeaderBg,
      borderRadius: 4,
      borderWidth: invoiceTokens.border.thin,
      borderColor: invoiceTokens.colors.lightBorder,
      marginBottom: invoiceTokens.spacing.md,
    },
    termsTitle: {
      fontSize: invoiceTokens.fontSize.xs,
      fontWeight: 'bold',
      color: accentColor,
      textTransform: 'uppercase',
      marginBottom: invoiceTokens.spacing.xxs,
    },
    termsText: {
      fontSize: invoiceTokens.fontSize.xs,
      color: invoiceTokens.colors.muted,
      lineHeight: 1.3,
    },
    footerRow: {
      position: 'absolute',
      bottom: 20,
      left: 28,
      right: 28,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingTop: invoiceTokens.spacing.xs,
      borderTopWidth: invoiceTokens.border.thin,
      borderTopColor: invoiceTokens.colors.lightBorder,
    },
    footerText: {
      fontSize: invoiceTokens.fontSize.xxs,
      color: invoiceTokens.colors.lightMuted,
    },
    watermark: {
      position: 'absolute',
      top: '40%',
      left: '20%',
      transform: 'rotate(-35deg)',
      opacity: 0.12,
      fontSize: 60,
      fontWeight: 'bold',
      color: '#000000',
    },
    copyLabel: {
      fontSize: invoiceTokens.fontSize.xxs,
      fontWeight: 'bold',
      color: '#dc2626',
      borderWidth: 1,
      borderColor: '#dc2626',
      paddingVertical: 1,
      paddingHorizontal: 4,
      borderRadius: 2,
      textTransform: 'uppercase',
    },
  });
