/**
 * Backward-compatibility facade for Indian Income Tax helpers.
 * Canonical implementation has been quarantined in @free-gst/financial-core
 */

import * as itr from '@free-gst/financial-core';

export {
  CURRENT_FY,
  OLD_REGIME_SLABS,
  OLD_REGIME_SLABS_SENIOR,
  OLD_REGIME_SLABS_SUPER_SENIOR,
  getOldRegimeSlabs,
  NEW_REGIME_SLABS_FY_2024_25,
  NEW_REGIME_SLABS_FY_2025_26,
  NEW_REGIME_SLABS,
  getNewRegimeSlabs,
  get87AConfig,
  getCapitalGainsConfig,
  DEDUCTION_CAPS,
  effectiveDeductionCap,
  computeSlabTax,
  computeSurcharge,
  computeRebate87A,
  computeCess,
  standardDeduction,
  computeAllowedDeductions,
  computeTax,
  compareRegimes,
  autoCategorize,
  parseBankStatement,
  compute44AD,
  compute44ADA,
  compute44AE,
  getAdvanceTaxSchedule,
  computeAdvanceTaxSchedule,
  compute234CInterest,
  compute234AInterest,
  compute234BInterest,
  buildITR4FieldMap,
} from '@free-gst/financial-core';

export type {
  TaxRegime,
  TaxSlab,
  Rebate87AConfig,
  CapitalGainsConfig,
  DeductionContext,
  SurchargeOptions,
  TaxComputationInputs,
  TaxComputationResult,
  RegimeComparisonResult,
  BankStatementParseResult,
  Presumptive44ADInput,
  Presumptive44ADResult,
  Presumptive44ADAInput,
  Presumptive44ADAResult,
  Presumptive44AEInput,
  Presumptive44AEResult,
  AdvanceTaxInstallment,
  AdvanceTaxRow,
  AdvanceTaxPayment,
  ITR4FieldMapRow,
  AutoCategoryRule,
} from '@free-gst/financial-core';

export default {
  CURRENT_FY: itr.CURRENT_FY,
  OLD_REGIME_SLABS: itr.OLD_REGIME_SLABS,
  OLD_REGIME_SLABS_SENIOR: itr.OLD_REGIME_SLABS_SENIOR,
  OLD_REGIME_SLABS_SUPER_SENIOR: itr.OLD_REGIME_SLABS_SUPER_SENIOR,
  getOldRegimeSlabs: itr.getOldRegimeSlabs,
  NEW_REGIME_SLABS_FY_2024_25: itr.NEW_REGIME_SLABS_FY_2024_25,
  NEW_REGIME_SLABS_FY_2025_26: itr.NEW_REGIME_SLABS_FY_2025_26,
  NEW_REGIME_SLABS: itr.NEW_REGIME_SLABS,
  getNewRegimeSlabs: itr.getNewRegimeSlabs,
  get87AConfig: itr.get87AConfig,
  getCapitalGainsConfig: itr.getCapitalGainsConfig,
  DEDUCTION_CAPS: itr.DEDUCTION_CAPS,
  effectiveDeductionCap: itr.effectiveDeductionCap,
  computeSlabTax: itr.computeSlabTax,
  computeSurcharge: itr.computeSurcharge,
  computeRebate87A: itr.computeRebate87A,
  computeCess: itr.computeCess,
  standardDeduction: itr.standardDeduction,
  computeAllowedDeductions: itr.computeAllowedDeductions,
  computeTax: itr.computeTax,
  compareRegimes: itr.compareRegimes,
  AUTO_CATEGORY_RULES: itr.AUTO_CATEGORY_RULES,
  autoCategorize: itr.autoCategorize,
  parseBankStatement: itr.parseBankStatement,
  compute44AD: itr.compute44AD,
  compute44ADA: itr.compute44ADA,
  compute44AE: itr.compute44AE,
  getAdvanceTaxSchedule: itr.getAdvanceTaxSchedule,
  ADVANCE_TAX_SCHEDULE: itr.ADVANCE_TAX_SCHEDULE,
  computeAdvanceTaxSchedule: itr.computeAdvanceTaxSchedule,
  compute234CInterest: itr.compute234CInterest,
  compute234AInterest: itr.compute234AInterest,
  compute234BInterest: itr.compute234BInterest,
  buildITR4FieldMap: itr.buildITR4FieldMap,
};
