/**
 * Centralized API endpoint route dictionary.
 */
export const ENDPOINTS = {
  BILLS: '/api/bills',
  BILL_BY_ID: (id: string) => `/api/bills/${encodeURIComponent(id)}`,
  CLIENTS: '/api/clients',
  CLIENT_BY_ID: (id: string) => `/api/clients/${encodeURIComponent(id)}`,
  PRODUCTS: '/api/products',
  PRODUCT_BY_ID: (id: string) => `/api/products/${encodeURIComponent(id)}`,
  EXPENSES: '/api/expenses',
  EXPENSE_BY_ID: (id: string) => `/api/expenses/${encodeURIComponent(id)}`,
  PURCHASES: '/api/purchases',
  PURCHASE_BY_ID: (id: string) => `/api/purchases/${encodeURIComponent(id)}`,
  RECURRING: '/api/recurring',
  RECURRING_BY_ID: (id: string) => `/api/recurring/${encodeURIComponent(id)}`,
  RECEIPTS: '/api/receipts',
  RECEIPT_BY_ID: (id: string) => `/api/receipts/${encodeURIComponent(id)}`,
  TEMPLATES: '/api/templates',
  TEMPLATE_BY_ID: (id: string) => `/api/templates/${encodeURIComponent(id)}`,
  PROFILES: '/api/profiles',
  PROFILE_BY_ID: (id: string) => `/api/profiles/${encodeURIComponent(id)}`,
  PROFILE: '/api/profile',
  META_KEY: (key: string) => `/api/meta/${encodeURIComponent(key)}`,
  META_INCREMENT: (key: string) => `/api/meta/${encodeURIComponent(key)}/increment`,
  EXPORT: '/api/export',
  IMPORT: '/api/import',
  SAVE_PDF: '/api/save-pdf',
  TRASH_PDF: '/api/trash-pdf',
  VERSION: '/api/version',
  CHECK_UPDATE: '/api/check-update',
  CONTROL_PANEL_STATUS: '/api/control-panel/status',
  CONTROL_PANEL_LAUNCH_SCRIPT: '/api/control-panel/launch-script',
  BACKUPS: '/api/backups',
  BACKUP_BY_DATE: (date: string) => `/api/backups/${encodeURIComponent(date)}`,
  BACKUP_RESTORE: (date: string) => `/api/backups/${encodeURIComponent(date)}/restore`,
  BACKUP_NOW: '/api/backups/now',
  TRASH: '/api/trash',
  TRASH_RESTORE: (id: string) => `/api/trash/${encodeURIComponent(id)}/restore`,
  TRASH_PURGE: (id: string) => `/api/trash/${encodeURIComponent(id)}`,
  HEALTH: '/api/health',
} as const;
